# Generated by Django 2.2.1 on 2019-05-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponserd', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('site', models.CharField(max_length=200)),
            ],
        ),
    ]
