# Generated by Django 2.2.1 on 2019-05-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='site',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='sponserd',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
