# Generated by Django 2.2.1 on 2019-05-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190518_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='site',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='sponserd',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='url',
            field=models.TextField(),
        ),
    ]
