# Generated by Django 2.2.1 on 2019-06-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190518_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='sponserd',
            new_name='sponsored',
        ),
    ]
